# from build as b import [build,test]
---
with:
  - build as b
  - notify as n
compose:
  - stage: build and test
    steps:
      - b.gradle_build
      - b."gradle unit and integ test"
    on_success:
      emit:
        - ${this.run}.success
    on_failure:
      continue: true
      emit:
        - ${this.run}.failure
      steps:
        - n.notify_slack "Failed!"
  launch:
    when: reponame.develop.merge
    expect:
      - repoName
      - projectName
      - testing
