# from build as b import [build,test]
---
with:
  - build as b
  - ""
compose:
  - stage: build and test
    steps:
      - b.gradle_build
      - b."gradle unit and integ test"
    on_success:
      emit:
        - ${this.run}.success
    on_failure:
      emit:
        - ${this.run}.failure
  launch:
    when: titan.develop.merge
    expect:
      - repoName
      - projectName
      - testing
